
services:

  #Flask service
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile.prod
    ports:
      - '5000:8080'
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      MARIADB_HOST: mariadb
      MARIADB_USER: ${DB_LOWP_USER}
      MARIADB_PASSWORD: ${DB_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_DBNAME}
      BASE_URL: 'https://pinboards.it'

  # MariaDb Service
  mariadb:
    image: bitnami/mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_LOWP_USER}
      MARIADB_PASSWORD: ${DB_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${DB_DBNAME}
      MARIADB_PORT_NUMBER: 3306
    volumes:
      - ./docker/mariadb/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf
      - ./docker/mariadb/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadata:/bitnami/mariadb/data

# Volumes
volumes:
  mariadata:

