# Production dockerfile
########## FIRST STEP: FRONTEND BUILD #######
FROM node:16 as frontendbuild

WORKDIR /frontend


#TODO: dockerignore required
COPY . .


# RUN npm ci --only=production
RUN npm ci
RUN npm run build

########## FINAL STEP: PRODUCTION IMAGE #######
FROM php:8.1.3-apache-buster

WORKDIR /var/www/html

COPY --from=frontendbuild /frontend/www ./
